// svelte-master-styles/src/pages/ColorsPage/ColorsPage.svelte
<script>
  import ContentHeader from "../../components/Header/ContentHeader.svelte"
  import SideMenu from "../../components/SideMenu/SideMenu.svelte"
  import Colors from "../../components/Colors/Colors.svelte"
  import { MAIN_CONTENT } from "../../classes/mainContent"
</script>

<div>
  <ContentHeader />
  <div class={MAIN_CONTENT}>
    <SideMenu currentMenu="colors" />
    <Colors />
  </div>
</div>

// react-master-styles/src/pages/ColorsPage/ColorsPage.tsx
import React from 'react'

import { ContentHeader } from '../../components/Header'
import { SideMenu } from '../../components/SideMenu'
import { Colors } from '../../components/Colors'
import { MAIN_CONTENT } from '../../classes/mainContent'

export const ColorsPage: React.FC = () => {
  return (
    <div>
      <ContentHeader />
      <div className={MAIN_CONTENT}>
        <SideMenu currentMenu='colors' />
        <Colors />
      </div>
    </div>
  )
}
