// vite-master-styles/src/App.vue
<script setup lang="ts">
import '@master/normal.css';
import '@master/styles'

import Colors from './components/Colors/Colors.vue';
</script>

<template>
  <div>
    <h1 className="font:40 font:heavy font:italic m:50 text:center">
      Hello Master Styles
    </h1>
    <Colors />
  </div>
</template>

// react-master-styles/src/App.tsx
import React from 'react'
import './App.css'
import { Colors } from './components/Colors'

const App: React.FC = () => {
  return (
    <div className='app'>
      <h1 className='font:40 font:heavy font:italic m:50 text:center'>
        Hello Master Styles
      </h1>
      <Colors />
    </div>
  )
}

export default App
