// svelte-master-styles/src/pages/AnimationsPage/AnimationsPage.svelte
<script>
  import ContentHeader from "../../components/Header/ContentHeader.svelte"
  import SideMenu from "../../components/SideMenu/SideMenu.svelte"
  import Animations from "../../components/Animations/Animations.svelte"
  import { MAIN_CONTENT } from "../../classes/mainContent"
</script>

<div>
  <ContentHeader />
  <div class={MAIN_CONTENT}>
    <SideMenu currentMenu="animations" />
    <Animations />
  </div>
</div>

// react-master-styles/src/pages/AnimationsPage/AnimationsPage.tsx
import React from 'react'

import { ContentHeader } from '../../components/Header'
import { SideMenu } from '../../components/SideMenu'
import { Animations } from '../../components/Animations'
import { MAIN_CONTENT } from '../../classes/mainContent'

export const AnimationsPage: React.FC = () => {
  return (
    <div>
      <ContentHeader />
      <div className={MAIN_CONTENT}>
        <SideMenu currentMenu='animations' />
        <Animations />
      </div>
    </div>
  )
}
