// nuxt-master-styles/components/Animations/AnimationDemo.vue
<template>
  <div class="d:flex flex:col w:full align-items:center">
    <code class="f:12">{{ animationClass }}</code>
    <div class="d:flex mt:25 justify-content:center">
      <div :class="animationClass + ' b:1;solid;blue-47 bg:blue-47/.1 p:30 r:5'" />
    </div>
  </div>
</template>

<script>
export default {
  name: 'AnimationDemo',
  props: {
    animationClass: {
      type: String,
      default: ''
    }
  }
}
</script>

// remix-master-styles/app/components/Animations/AnimationDemo.tsx
import React from 'react'

export interface AnimationDemoProps {
  animationClass: string
}

export const AnimationDemo: React.FC<AnimationDemoProps> = (props: AnimationDemoProps) => {
  return (
    <div className='d:flex flex:col w:full align-items:center'>
      <code className='f:12'>{props.animationClass}</code>
      <div className='d:flex mt:25 justify-content:center'>
        <div className={`${props.animationClass} b:1;solid;blue-47 bg:blue-47/.1 p:30 r:5`} />
      </div>
    </div>
  )
}
