// next-master-styles/pages/index.tsx
import type { NextPage } from 'next'
import { Colors } from '../components/Colors'
import '@master/styles';

const Home: NextPage = () => {
  return (
    <div>
      <h1 className="font:40 font:heavy font:italic m:50 text:center">
          Hello World
      </h1>
      <Colors />
    </div>
  )
}

export default Home

// nuxt-master-styles/pages/index.vue
<template>
  <div>
    <h1 class="font:40 font:heavy font:italic m:50 text:center">
      Hello Master Styles
    </h1>
    <Colors />
  </div>
</template>

<script lang="ts">
import Vue from 'vue'
import '@master/normal.css'
import '@master/styles'

export default Vue.extend({
  name: 'IndexPage'
})
</script>
