// remix-master-styles/app/components/Colors/ColorBlock.tsx
import React from 'react'

export interface ColorBlockProps {
  colorName: string
}

export const ColorBlock: React.FC<ColorBlockProps> = (props: ColorBlockProps) => {
  return (
    <div>
      <div className={`h:40 background-color:${props.colorName}`} />
      <div className='mt:5 d:flex align-items:center'>
        <span className='f:14 f:semibold'>{props.colorName}</span>
      </div>
    </div>
  )
}

// vite-master-styles/src/components/Colors/ColorBlock.vue
<template>
  <div>
    <div class="h:40" :class="'background-color:' + colorName" />
    <div class="mt:5 d:flex align-items:center">
      <span class="f:14 f:semibold">{{ colorName }}</span>
    </div>
  </div>
</template>

<script>
export default {
  name: 'color-block',
  props: {
    colorName: {
      type: String,
      default: 'black'
    }
  }
}
</script>
